---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: test
  label: Test
  create: all
  match: "**/*"
- type: directory
  path: stuff
  label: New section
  create: all
  match: "**/*"
- type: directory
  path: ''
  label: YAML
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - yaml
- type: directory
  path: content
  label: Posts
  create: all
  match: "**/*"
- type: document
  path: site-config.json
  label: Config
upload_dir: uploads2
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: npm run forestry:preview
