---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: directory
  path: ''
  label: YAML
  create: all
  match: "**/*"
  new_doc_ext: yaml
  templates:
  - yaml
- type: directory
  path: content
  label: Posts
  create: all
  match: "**/*"
- type: document
  path: site-config.json
  label: Config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
